import Head from "next/head";
import Header from "../components/header";
import SectionA from "../components/sectionA";
import SectionB from "../components/sectionB";
import Footer from "../components/footer";
import { useRef } from "react";
import ToTop from "../components/toTop";

export default function Home(lastDraw) {
  const scrollTargetElementRef = useRef(null);

  return (
    <div ref={scrollTargetElementRef}>
      <Head>
        <title>CoinSino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="top"
        className="bg-[url('/images/bg.png')] bg-center bg-no-repeat "
      >
        <ToTop scrollTargetElementRef={scrollTargetElementRef} />
        <Header />
        <SectionA />
      </div>

      <SectionB />

      <Footer scrollTargetElementRef={scrollTargetElementRef} />
    </div>
  );
}
