import Head from "next/head";
import Header from "../components/header";
import SectionA from "../components/sectionA";
import SectionB from "../components/sectionB";
import Footer from "../components/footer";
import { useRef } from "react";
import ToTop from "../components/toTop";

export function getServerSideProps() {
  const now = new Date();
  const drawUtc = new Date(
    Date.UTC(now.getFullYear(), now.getMonth(), now.getDate(), 12)
  );
  //  jsjds

  const month = drawUtc.toLocaleString("default", { month: "short" });
  const date = drawUtc.getDate();
  const year = drawUtc.getFullYear();
  const hour = drawUtc.getHours();
  const minute = drawUtc.getMinutes();
  const second = drawUtc.getSeconds();
  const amPm = hour >= 12 ? "PM" : "AM";
  const lastDraw = { month, date, year, hour, minute, second, amPm };

  return {
    props: lastDraw,
  };
}

export default function Home(lastDraw) {
  const scrollTargetElementRef = useRef(null);

  return (
    <div ref={scrollTargetElementRef}>
      <Head>
        <title>CoinSino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="top"
        className="bg-[url('/images/bg.png')] bg-center bg-no-repeat "
      >
        <ToTop scrollTargetElementRef={scrollTargetElementRef} />
        <Header />
        <SectionA />
      </div>

      <SectionB lastDraw={lastDraw} />

      <Footer scrollTargetElementRef={scrollTargetElementRef} />
    </div>
  );
}
